name: 🐛 Bug report
description: Describe a problem

body:
  - type: markdown
    attributes:
      value: |
        Some general tips:

        - Is this really a problem?
        - Is this a problem here?
        - Can this be solved in a different way?

  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)
          required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected packages and versions
      description: Please test using the latest version of the relevant packages to make sure your issue has not already been fixed.
    validations:
      required: true

  - type: input
    id: runnable-example
    attributes:
      label: Link to runnable example
      description: |
        Link to repository or sandbox with runnable example of the issue.

        Some starters:

        | description | codesandbox | stackblitz |
        | - | - | - |
        | remark only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) |
        | remark and rehype (for markdown to html) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) |
        | react-markdown | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) |
        | remark only (for markdown to markdown, deno) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-deno) | :no_entry: |

        Alternatively, use the next section *Steps to reproduce*.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How did this happen? Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true

  - attributes:
      label: Affected runtime and version
      description: |
        What runtime are you using (such as `node@22.9`, `deno@1.12.2`)?
        Please test using the latest version.
    id: runtime
    type: input
    validations:
      required: true
  - attributes:
      description: |
        What package manager are you using (such as `npm@10.8.1`)?
        Please test using the latest version.
      label: Affected package manager and version
    id: package-manager
    type: input
    validations:
      required: false

  - attributes:
      description: |
        What operating system are you using (such as `macOS Sequoia 15`)?
        Please test using the latest version.
      label: Affected OS and version
    id: operating-system
    type: input
    validations:
      required: false

  - type: dropdown
    id: build-tools
    attributes:
      label: Build and bundle tools
      description: What, if any, tools are used to build or bundle the project?
      multiple: true
      options:
        - Vite
        - Webpack
        - Rollup
        - esbuild
        - Parcel
        - Create React App
        - Gatsby
        - Next.js
        - Remix
        - Docusaurus
        - Storybook
        - Other (please specify in steps to reproduce)
    validations:
      required: false
