body:
  - attributes:
      value: |
        Some general tips:

        * is this really a problem?
        * is this a problem here?
        * can this be solved in a different way?
        * can this be contributed as a PR with a failing test instead?
    type: markdown
  - attributes:
      label: Initial checklist
      options:
        - label: I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
          required: true
        - label: I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
          required: true
        - label: I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
          required: true
        - label: I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)
          required: true
    id: initial-checklist
    type: checkboxes
  - attributes:
      description: |
        Which packages cause the bug?
        Please test using latest versions.
        Example: `some-package@1.2.3`.
      label: Affected package
    id: affected-versions
    type: input
    validations:
      required: true
  - attributes:
      description: |
        How did this happen?

        Provide a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
        Link to a repository or sandbox or show the code here.
        Remove everything that is not needed.
        Use plain Node and npm if possible.

        Some starters:

        | description | codesandbox | stackblitz |
        | - | - | - |
        | `remark` only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-vite) |
        | `remark` and `rehype` (for markdown to HTML) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite) |
        | `react-markdown` | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-vite) |
        | `remark` only (for markdown to markdown, deno) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-deno) | :no_entry: |
      label: Steps to reproduce
    id: steps-to-reproduce
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        What happens?
        What is wrong with the current behavior?
      label: Actual behavior
    id: actual-behavior
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        What should happen instead?
        Why should that happen?
        Why is that better than the current behavior?
      label: Expected behavior
    id: expected-behavior
    type: textarea
    validations:
      required: true
  - attributes:
      label: Runtime
      description: |
        What runtime are you using?
        Please test using latest versions.
        Example: `node@23.2.0` or `Chrome 131.0.6778.86`.
    id: runtime
    type: input
    validations:
      required: false
  - attributes:
      description: |
        What package manager are you using?
        Please test using latest versions.
        Example: `npm@10.9.0`.
      label: Package manager
    id: package-manager
    type: input
    validations:
      required: false
  - attributes:
      description: |
        What operating system are you using?
        Please test using latest versions.
        Example: `macOS Sequoia 15.1.1`.
      label: Operating system
    id: operating-system
    type: input
    validations:
      required: false
  - attributes:
      description: |
        What tools are used to build or bundle the project?
        Please test using latest versions.
      label: Build and bundle tools
      multiple: true
      options:
        - Astro
        - CRA (Create React App)
        - Docusaurus
        - Gatsby
        - Next.js
        - Parcel
        - Remix
        - Rollup
        - Vite
        - esbuild
        - swc
        - webpack
        - other (please specify in steps to reproduce)
    id: build-tools
    type: dropdown
    validations:
      required: false
description: Report a bug
name: 🐛 Bug
